---

- name: Ensure install directory exists
  become: true
  ansible.builtin.file:
    path: "/opt/{{ app.name | lower }}/"
    state: "directory"
    mode: "0755"
    owner: "root"
    group: "root"

- name: "Set up {{ app.name }}"
  become: true
  ansible.builtin.get_url:
    url: "{{ app.download_url }}"
    dest: "/opt/{{ app.name | lower }}/{{ app.id }}.{{ app.archive }}"
    mode: "0755"
    owner: "root"
    group: "root"

- name: Install dependencies
  become: true
  when: app.dependencies[ansible_os_family] is defined
  loop: "{{ app.dependencies[ansible_os_family] }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"

- name: Create desktop launcher
  become: true
  ansible.builtin.template:
    src: "{{ app.id }}.desktop.j2"
    dest: "/usr/share/applications/{{ app.id }}.desktop"
    mode: "0755"
    owner: "root"
    group: "root"

- name: "Set up icon {{ app.name }}"
  become: true
  ansible.builtin.copy:
    src: "{{ app.id }}.svg"
    dest: "/usr/share/icons/hicolor/scalable/apps/{{ app.id }}.svg"
    mode: "0644"
    owner: "root"
    group: "root"
  register: icon_result

- name: Update icon cache
  become: true
  when: icon_result.changed
  ansible.builtin.command:
    cmd: gtk-update-icon-cache /usr/share/icons/hicolor/
  register: icon_update_result
  changed_when: icon_update_result.rc == 0

...
