---

# Empty task file to initialize role library and pre-load all variables


- name: Initialize role variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_items:
    - ../../defaults/main/common.yml
    - ../../defaults/main/extensions.yml
    - ../../defaults/main/themes.yml
    - ../../vars/main.yml

...
