---

- name: Create install directory
  become: true
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: "directory"
    mode: "0744"
    owner: "root"
    group: "root"

- name: "Download and extract {{ theme.name }}"
  become: true
  ansible.builtin.unarchive:
    src: "{{ theme.repo_url }}"
    dest: "{{ install_dir }}/"
    remote_src: true
  register: download_result
  until: download_result is succeeded
  retries: 5
  delay: 10

- name: Update installer permissions
  become: true
  ansible.builtin.file:
    path: "{{ (install_dir, theme.install_dir, theme.installer) | ansible.builtin.path_join }}"
    mode: "0755"

- name: Install theme dependencies
  become: true
  when: theme.dependencies is defined
  loop: "{{ theme.dependencies[ansible_os_family] }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: "Install theme"
  become: true
  ansible.builtin.command:
    cmd: "{{ theme.install_cmd }}"
  args:
    chdir: "{{ install_dir }}/{{ theme.install_dir }}"
  register: install_result
  changed_when: install_result.rc == 0

- name: Remove install dir
  become: true
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: absent

...
