---

- name: Get installed GNOME themes
  ansible.builtin.find:
    paths: "{{ theme_paths }}"
    file_type: directory
    depth: 1
  register: theme_dirs

- name: Set themes list
  ansible.builtin.set_fact:
    themes: "{{ theme_dirs.files | map(attribute='path') | map('basename') | list }}"

- name: Install themes
  loop: "{{ gnome_themes }}"
  loop_control:
    label: "{{ theme.name }}"
    loop_var: theme
  when: theme.name not in themes
  ansible.builtin.include_tasks:
    file: install_themes.yml

...
