---

# gnome base setup

- name: Install Gnome packages
  when: item not in ansible_facts.packages
  loop: "{{ gnome_packages[ansible_os_family] | flatten(1) }}"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Remove obsolete Gnome packages
  become: true
  loop: "{{ obsolete_packages[ansible_os_family] | flatten(1) }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent

- name: Create system default resolution path
  become: true
  ansible.builtin.file:
    path: "{{ gdm_monitor_config_sys_path[ansible_os_family] }}"
    state: directory
    mode: "0700"

- name: Set system default resolution
  become: true
  ansible.builtin.template:
    src: monitors.xml.j2
    dest: "{{ gdm_monitor_config_sys_path[ansible_os_family] }}/monitors.xml"
    mode: "0644"
    owner: "{{ gdm_user_name[ansible_distribution] }}"
    group: "{{ gdm_user_name[ansible_distribution] }}"

- name: Create user default resolution path
  ansible.builtin.file:
    path: "{{ gdm_monitor_config_user_path }}"
    state: directory
    mode: "0700"

- name: Set user default resolution
  become: true
  ansible.builtin.template:
    src: monitors.xml.j2
    dest: "{{ gdm_monitor_config_user_path }}/monitors.xml"
    mode: "0644"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_effective_group_id }}"

- name: Get Gnome version
  ansible.builtin.shell:
    cmd: "gnome-shell --version | awk '{print $3}' | cut -d'.' -f1"
  register: gnome_major_version
  changed_when: false

...
