---

# variables for basic gnome config

user_install_dir: "{{ (ansible_env.HOME, 'install') | ansible.builtin.path_join }}"
gnome_enable_reboot: true

additional_rhel_repos:
  - name: rpmfusion-free
    gpg_key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-el-{{ ansible_distribution_major_version }}"
    src: "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - name: rpmfusion-nonfree
    gpg_key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-el-{{ ansible_distribution_major_version }}"
    src: "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

gnome_packages:
  "default": &gnome_pkgs_default
    - gnome-shell
    - gnome-themes-extra # includes Adwaita-dark
    - gnome-terminal
    - gnome-system-monitor
    - gnome-software
    - gnome-tweaks
    - gnome-user-docs
    - gnome-photos
    - gnome-font-viewer
    - gnome-characters
    - gnome-devel-docs
    - gnome-disk-utility
    - baobab
  "RedHat":
    - *gnome_pkgs_default
    - gnome-extensions-app
    - gnome-control-center-filesystem
  "Debian":
    - *gnome_pkgs_default
    - gnome-shell-extension-prefs
    - gnome-control-center

obsolete_packages:
  "default": &osbolete_pkgs_default
    - gnome-tour
    - gnome-shell-extension-background-logo
    - gnome-software-plugin-snap
    - gnome-startup-applications
  "RedHat":
    - *osbolete_pkgs_default
    - gnome-remote-desktop
  "Debian":
    # INFO gnome-remote-desktop is a part of gnome-control-center package
    - *osbolete_pkgs_default

gdm_config_file:
  "CentOS": "/etc/gdm/custom.conf"
  "AlmaLinux": "/etc/gdm/custom.conf"
  "Rocky": "/etc/gdm/custom.conf"
  "Ubuntu": "/etc/gdm3/custom.conf"
  "Debian": "/etc/gdm3/daemon.conf"

gnome_base_settings:
  "dconf_default": &dconf_default
    # INFO obsolete if user theme gets added
    # "/org/gnome/desktop/interface/gtk-theme": "'Adwaita-dark'"
    "/system/locale/region": "'en_GB.UTF-8'"
    "/org/gnome/desktop/interface/enable-hot-corners": "false"
    "/org/gnome/desktop/input-sources/sources": "[('xkb', 'de'), ('xkb', 'us')]"
    "/org/gnome/desktop/input-sources/sources/per-window": "false"
    "/org/gnome/desktop/input-sources/mru-sources": "[['xkb', 'de'], ['xkb', 'us']]"
    "/org/gnome/desktop/input-sources/xkb-options": "['caps:none']"
    "/org/gnome/desktop/wm/keybindings/activate-window-menu": "@as []"
    "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar": "'minimize'"
    "/org/gnome/mutter/attach-modal-dialogs": "false"
    "/org/gnome/mutter/center-new-windows": "false"
    "/org/gnome/mutter/edge-tiling": "false"
    "/org/gnome/desktop/interface/clock-show-weekday": "true"
    "/org/gnome/desktop/interface/font-name": "'Cantarell Bold 11'"
    "/org/gnome/desktop/wm/preferences/titlebar-font": "'Carlito Bold Italic 11'"
    "/org/gnome/tweaks/show-extensions-notice": "false"
    "/org/gnome/desktop/wm/preferences/button-layout": "'close,maximize,minimize:appmenu'"
    "/org/gnome/software/download-updates": "false"
    "/org/gnome/software/first-run": "false"
  "40":
    <<: *dconf_default
  "42":
    # INFO obsolete if user theme gets added
    # "/org/gnome/shell/extensions/user-theme/name": "'Yaru-magenta-dark'"
    <<: *dconf_default
    "/org/gnome/desktop/interface/color-scheme": "'prefer-dark'"
  "43":
    <<: *dconf_default
    "/org/gnome/desktop/interface/color-scheme": "'prefer-dark'"
    "/org/gnome/desktop/privacy/old-files-age": "30"
    "/org/gnome/desktop/privacy/recent-files-max-age": "30"
    "/org/gnome/desktop/privacy/remove-old-temp-files": "true"
    "/org/gnome/desktop/privacy/remove-old-trash-files": "true"
