---

- name: Create and configure gnome desktop
  hosts: client

  # TODO local testing only
  # debugger: on_failed

  roles:
    - role: ansible-gnome
      tasks_from: main
      gnome_setup_state: present

...
