---

dependency:
  name: galaxy
driver:
  name: vagrant
  parallel: true
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: Alma9
    box: almalinux/9
    memory: 4096
    cpus: 2
    provider_options:
      gui: true
    linked_clone: true
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.10"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
      - "customize ['modifyvm', :id, '--vram', '256']"
      - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
      - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
      - "customize ['modifyvm', :id, '--clipboard-mode', 'bidirectional']"
      - "customize ['modifyvm', :id, '--draganddrop', 'bidirectional']"
    groups:
      - client
  - name: Ubuntu2210
    box: ubuntu/jammy64
    memory: 4096
    cpus: 2
    provider_options:
      gui: true
    linked_clone: true
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.20"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
      - "customize ['modifyvm', :id, '--vram', '256']"
      - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
      - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
      - "customize ['modifyvm', :id, '--clipboard-mode', 'bidirectional']"
      - "customize ['modifyvm', :id, '--draganddrop', 'bidirectional']"
    groups:
      - client
provisioner:
  name: ansible
  env:
    # ANSIBLE_VERBOSITY: 3
    ANSIBLE_DIFF_ALWAYS: false
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      diff: True
      gathering: smart
      fact_caching_timeout: 3600
      fact_caching: jsonfile
      fact_caching_connection: /tmp/ansible_fact_cache
      stdout_callback: debug
      callbacks_enabled: ansible.posix.profile_tasks
    connection:
      # WARNING disable "requiretty" in hosts sudoers file on case of errors
      pipelining: true
    env:
      ANSIBLE_FORCE_COLOR: "true"
verifier:
  name: ansible
scenario:
  test_sequence:
      - dependency
      - syntax
      - create
      - prepare
      - converge
      - idempotence
      - side_effect
      - verify
      - cleanup
      - destroy

...
